### ISSUE TITLE
Argumenty funkce quadtree nemusíš pojmenovávat, pokud je zadáváš všechny

### ISSUE THREAD

**Issue by xtompok** [lnenicp/uvod_do_programovani#15]
Pojmenované argumenty se hodí, pokud nějaký potřebuješ vynechat, nebo z názvu proměnné, kterou funkci předáváš, není jasné, co reprezentuje. Takto to akorát prodlužuje kód a zhoršuje přehlednost.

**Comment by lnenicp** [comment]
připadalo mi to přehlednější, ale opravila jsem
