### ISSUE TITLE
output_json = input_json dělá jiné věci, než bys čekala

### ISSUE THREAD

**Issue by xtompok** [lnenicp/uvod_do_programovani#16]
Tento výraz pouze vytvoří novou proměnnou `output_json`, která ukazuje na stejný slovník jako `input_json`. Cokoli změníš v jednom slovníku, objeví se i v druhém.
Zde to nevadí, ale doporučoval bych, aby proměnná existovala pouze jedna, aby to nesvádělo k tomu si myslet, že jde o různé slovníky.

**Comment by lnenicp** [comment]
pro mě je srozumitelnější tento zápis - kdybych zapisovala do input_json, bylo by to pro mě více matoucí
